name: MailHog E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongo:
        image: mongo
        ports:
          - 27017:27017

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    env:
      MAIL_HOST: localhost
      MAIL_PORT: 1025
      MAIL_USER: test
      MAIL_PASS: test
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:admin@localhost:5432/postgres
      MONGO_URL: mongodb://localhost:27017/testdb

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run E2E Tests
        run: npm run test:e2eSql
